### ISSUE TITLE
Does not compile in react-native version 0.61.2 (Android) : MapsPackage() not found

### ISSUE THREAD

**Issue by royken** [react-native-community/react-native-maps#3162]
# Bug
Hi all,
When I add react-native-maps in  my project, the code no more compiles and I am getting this error : 

`Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081
C:\Users\user\Documents\React\appName\android\app\build\generated\rncli\src\main\java\com\facebook\react\PackageList.java:36: error: package com.airbnb.android.react.maps does not exist
import com.airbnb.android.react.maps.MapsPackage;
                                    ^
C:\Users\user\Documents\React\appName\android\app\build\generated\rncli\src\main\java\com\facebook\react\PackageList.java:109: error: cannot find symbol
      new MapsPackage(),
          ^
  symbol:   class MapsPackage
  location: class PackageList
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 33s`

## Environment info

React native info output:

```bash
 System:
    OS: Windows 10
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 2.23 GB / 15.88 GB
  Binaries:
    Node: 10.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.19.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  SDKs:
    Android SDK:
      API Levels: 22, 23, 25, 26, 27, 28
      Build Tools: 22.0.1, 27.0.3, 28.0.2, 28.0.3, 29.0.2
      System Images: android-23 | Google APIs Intel x86 Atom, android-26 | Google APIs Intel x86 Atom
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.2 => 0.61.2
```

Library version: 0.26.1

## Steps To Reproduce

1. Add maps library : npm install react-native-maps --save-exact
2. Define dependencies in build.gradle file: 
`implementation "com.google.android.gms:play-services-maps:16.1.0"`
3. Add apki key in manifest
```
<application>
   <meta-data
     android:name="com.google.android.geo.API_KEY"
     android:value="Your Google maps API Key Here"/>
</application>
```
4. build the app with  :
`react-native run-android`

**Comment by mixa63rus** [comment]
I have same issue. How did you solve it?

**Comment by yahao87** [comment]
@royken
I have same issue. How did you solve it?

**Comment by royken** [comment]
@yahao87 and @mixa63rus  i downgraded to version 0.26.0 of `react-native-maps` and replaced play-services-maps in build.dradle to use this one :`implementation "com.google.android.gms:play-services-maps:16.0.0"`

**Comment by EricMcRay** [comment]
If you don't have `supportLibVersion` setting in your gradle, it crashes `react-native-maps` gradle and gradle don't import the package. There is a string manipulation over `supportLibVersion` that causes the crash. You check the line at the below link.

https://github.com/react-native-community/react-native-maps/blob/v0.26.1/lib/android/build.gradle#L20

I solved the issue by adding `supportLibVersion` setting to `android/build.gradle`.  Like:

```
buildscript {
    ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 28
        googlePlayServicesVersion = "16.0.0"
        androidMapsUtilsVersion = "0.5+"
        supportLibVersion = '28.0.0' <--
    }
}
```

**Comment by mailmevenkat** [comment]
> If you don't have `supportLibVersion` setting in your gradle, it crashes `react-native-maps` gradle and gradle don't import the package. There is a string manipulation over `supportLibVersion` that causes the crash. You check the line at the below link.
> 
> https://github.com/react-native-community/react-native-maps/blob/v0.26.1/lib/android/build.gradle#L20
> 
> I solved the issue by adding `supportLibVersion` setting to `android/build.gradle`. Like:
> 
> ```
> buildscript {
>     ext {
>         buildToolsVersion = "28.0.3"
>         minSdkVersion = 16
>         compileSdkVersion = 28
>         targetSdkVersion = 28
>         googlePlayServicesVersion = "16.0.0"
>         androidMapsUtilsVersion = "0.5+"
>         supportLibVersion = '28.0.0' <--
>     }
> }
> ```
> 
> Fixed at #3106
> Can be relative to #3234 and #3166

Thank you, been trying for hours together to get it working and then boom this worked!
