### ISSUE TITLE
Error when running Jest tests

### ISSUE THREAD

**Issue by stdavis** [react-native-community/react-native-maps#2918]
# Bug
Jest tests are failing after upgrading from 0.22.1 to 0.24.2 (via Expo upgrade from 32 to 33). The following error message is returned:
```bash
TypeError: this.map.setNativeProps is not a function

      at MapView.setNativeProps [as _updateStyle] (node_modules/react-native-maps/lib/components/MapView.js:557:14)
      at MapView._updateStyle [as componentDidMount] (node_modules/react-native-maps/lib/components/MapView.js:551:12)
      at commitLifeCycles (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:9432:22)
      at commitAllLifeCycles (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10829:7)
      at Object.invokeGuardedCallbackImpl (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2302:10)
      at invokeGuardedCallback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2480:31)
      at commitRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11041:7)
      at node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12492:5
      at Object.unstable_runWithPriority (node_modules/scheduler/cjs/scheduler.development.js:255:12)
      at completeRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12491:13)
```

## Environment info
```bash
Expo CLI 2.20.0 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
      Yarn: 1.16.0 - ~/.nvm/versions/node/v10.15.3/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v10.15.3/bin/npm
    IDEs:
      Android Studio: 3.4 AI-183.5429.30.34.5452501
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      @storybook/react-native: 5.1.3 => 5.1.3 
      expo: ^33.0.0 => 33.0.6 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8 
    npmGlobalPackages:
      expo-cli: 2.20.0
```

Library version: 0.24.2

## Steps To Reproduce
I've created a simple project that reproduces the error:
1. `git clone https://github.com/stdavis/react-native-maps-issue`
1. `cd react-native-maps-issue`
1. `yarn`
1. `yarn test`

Thanks for the awesome project!

**Comment by fpyir** [comment]
Same here, the code the test runs is:
```
import React from 'react';
import MapView from 'react-native-maps';
import {View} from "react-native";

export default function () {
  return (
    <View>
      <MapView/>
    </View>
  );
}
```
And the test is:
```
import React from 'react';
import { render } from '@testing-library/react-native';
import TestMap from '../TestMap';

describe('TestMap', () => {
  it('should render without crashing', () => {
    const { asJSON } = render(<TestMap />) as any;
    expect(asJSON()).toMatchSnapshot();
  });
});
```

**Comment by aiham** [comment]
This happens because react-native-maps is rendering a native component, which needs to be mocked out.

```jest.mock('react-native-maps', () => {
  const { View } = require('react-native');
  const MockMapView = (props: any) => {
    return <View>{props.children}</View>;
  };
  const MockMarker = (props: any) => {
    return <View>{props.children}</View>;
  };
  return {
    __esModule: true,
    default: MockMapView,
    Marker: MockMarker,
  };
});```

**Comment by stdavis** [comment]
@aiham That fix worked for me. Thanks for the tip! 

I still wonder if this is something that could be fixed at the project level without requiring the user to mock. But I'll close this issue for now.

**Comment by JManuelMT** [comment]
@aiham it didn't work for me :/

**Comment by slavikdenis** [comment]
I ended up using this.

```
jest.mock('react-native-maps', () => {
  const { Component } = require('react');
  const { View } = require('react-native');

  class MockMapView extends Component {
    render() {
      return <View>{this.props.children}</View>;
    }
  }

  class MockMarker extends Component {
    render() {
      return <View>{this.props.children}</View>;
    }
  }

  const mockMapTypes = {
    STANDARD: 0,
    SATELLITE: 1,
    HYBRID: 2,
    TERRAIN: 3,
    NONE: 4,
    MUTEDSTANDARD: 5,
  };

  return {
    __esModule: true,
    default: MockMapView,
    Marker: MockMarker,
    MAP_TYPES: mockMapTypes,
    PROVIDER_DEFAULT: 'default',
    PROVIDER_GOOGLE: 'google',
  };
});
```

I used `Component` instead of a Functional component because of this warning:
`Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?  `

**Comment by crisecheverria** [comment]
> I ended up using this.
> 
> ```
> jest.mock('react-native-maps', () => {
>   const { Component } = require('react');
>   const { View } = require('react-native');
> 
>   class MockMapView extends Component {
>     render() {
>       return <View>{this.props.children}</View>;
>     }
>   }
> 
>   class MockMarker extends Component {
>     render() {
>       return <View>{this.props.children}</View>;
>     }
>   }
> 
>   const mockMapTypes = {
>     STANDARD: 0,
>     SATELLITE: 1,
>     HYBRID: 2,
>     TERRAIN: 3,
>     NONE: 4,
>     MUTEDSTANDARD: 5,
>   };
> 
>   return {
>     __esModule: true,
>     default: MockMapView,
>     Marker: MockMarker,
>     MAP_TYPES: mockMapTypes,
>     PROVIDER_DEFAULT: 'default',
>     PROVIDER_GOOGLE: 'google',
>   };
> });
> ```
> 
> I used `Component` instead of a Functional component because of this warning:
> `Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()? `
> 
> **EDIT:**
> 
> Extended the components a bit to have more props on snapshots like this:
> 
> ```
>   class MockMapView extends Component {
>     render() {
>       const { testID, children, ...props } = this.props;
> 
>       return (
>         <View testID={testID} {...props}>
>           {children}
>         </View>
>       );
>     }
>   }
> 
>   class MockMarker extends Component {
>     render() {
>       const { testID, children, ...props } = this.props;
> 
>       return (
>         <View testID={testID} {...props}>
>           {children}
>         </View>
>       );
>     }
>   }
> ```

Have the same but cant find the testID when using getByTestId from RN Testing Library

**Comment by moonderek** [comment]
Here's an example using a Functional Component with forwardRef.

 Includes examples for mocking methods like `getMapBoundaries`, `getCamera` for the MockMapView and `redraw` for the MockMarker.





```
jest.mock('react-native-maps', () => {
  const { View } = require('react-native');
  const React = require('react');

  const MockMapView = React.forwardRef(
    ({ testID, children, ...props }, ref) => {
      if (ref?.current) {
        ref.current = {
          getMapBoundaries: async () => ({
            northEast: {
              latitude: 2,
              longitude: 2,
            },
            southWest: {
              latitude: 1,
              longitude: 1,
            },
          }),
          getCamera: async () => ({
            center: {
              latitude: 2,
              longitude: 2,
            },
            heading: 1,
            pitch: 1,
            zoom: 1,
            altitude: 1,
          }),
          animateCamera: () => {},
        };
      }

      return (
        <View testID={testID} {...props}>
          {children}
        </View>
      );
    },
  );

  const MockMarker = React.forwardRef(({ testID, children, ...props }, ref) => {
    if (ref?.current) {
      ref.current = {
        redraw: () => {},
      };
    }

    return (
      <View testID={testID} {...props}>
        {children}
      </View>
    );
  });

  const mockMapTypes = {
    STANDARD: 0,
    SATELLITE: 1,
    HYBRID: 2,
    TERRAIN: 3,
    NONE: 4,
    MUTEDSTANDARD: 5,
  };

  return {
    __esModule: true,
    default: MockMapView,
    Marker: MockMarker,
    MAP_TYPES: mockMapTypes,
    PROVIDER_DEFAULT: 'default',
    PROVIDER_GOOGLE: 'google',
  };
});
```

**Comment by rajkumarbade** [comment]
I have used below code to mock the maps but still getting this error

 TypeError: this.map.animateCamera is not a function
      109 |         zoom: 10,
      110 |       };
    > 111 |       this.map.animateCamera(camera);
          |                ^
      112 |     }
      113 |   }
      114 |
      
      
jest.mock('react-native-maps', () => {
  const react = require('react');
  const { View } = require('react-native');
  const MockMapView = react.forwardRef(({ children, ...props }, ref) => {
    ref.current = {
      animateCamera: jest.fn(),
    };
    return (<View ref={ ref } testID='repairRequestLocation_mapView' { ...props }>{ children }</View>);
  });
   return {
    __esModule: true,
    default: MockMapView,
  };
});
anyone has a suggestion for this?
